---
- name: nginx role
  tags:
    - nginx
  block:

  # assert
  - name: Assertions
    ansible.builtin.assert:
      that:
      - ansible_facts['distribution_major_version'] is defined 
      - ansible_facts['os_family'] is defined

  # install
  - when: nginx_apt_state == "present"
    block:

    # repo key
    - name: Copy repo key
      become: true
      ansible.builtin.copy:
        src: nginx.gpg
        dest: /etc/apt/keyrings/nginx.gpg
        owner: root
        group: root
        mode: u=rw,g=r,o=r

    # add repo
    - name: Add repo nginx
      when: 
      - ansible_facts['os_family'] == 'Debian'
      - ansible_facts['distribution_major_version'] == '12'
      become: true
      ansible.builtin.deb822_repository:
        name: nginx
        types: deb
        architectures: amd64
        uris: http://nginx.org/packages/debian
        suites: bookworm
        components: nginx
        enabled: true
        signed_by: /etc/apt/keyrings/nginx.gpg
      register: add_repo
    
    # update
    - name: Update apt cache
      when: add_repo.changed
      become: true
      ansible.builtin.apt:
        update_cache: true

    # install
    - name: Install nginx
      become: true
      ansible.builtin.apt:
        update_cache: false
        state: present
        name: nginx

  # state == absent
  - when: nginx_apt_state == "absent"
    block:

    # remove 
    - name: Apt remove nginx
      become: true
      ansible.builtin.apt:
        state: absent
        name: nginx

  # cp sites
  - when: nginx_config_sites_enabled | length > 0
    block:

    - name: Copy to /etc/nginx/sites-available {{ nginx_config_sites_enabled }}
      become: true
      loop: "{{ nginx_config_sites_enabled }}" # ["sites/ziska/test.local.conf"]
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /etc/nginx/sites-available # item.split('/')[-1]

    # link
    - name: Link to /etc/nginx/sites-enabled {{ nginx_config_sites_enabled }}
      become: true
      loop: "{{ nginx_config_sites_enabled }}"
      ansible.builtin.file:
        src: "/etc/nginx/sites-available/{{ item.split('/')[-1] }}" # sites/ziska/test.local.conf --> test.local.conf
        dest: /etc/nginx/sites-enabled/{{ item.split('/')[-1] }}
        state: link

  # rm sites
  - when: nginx_config_sites_disabled | length > 0
    block:

    # rm
    - name: Remove from /etc/nginx/sites-enabled {{ nginx_config_sites_disabled }}
      become: true
      loop: "{{ nginx_config_sites_disabled }}"
      ansible.builtin.file:
        path: "/etc/nginx/sites-enabled/{{ item }}"
        state: absent