---
- name: nginx role
  tags:
    - nginx
  block:

  # assert
  - name: Assertions
    ansible.builtin.assert:
      that:
      - ansible_facts['distribution_major_version'] is defined 
      - ansible_facts['os_family'] is defined

  # install
  - ansible.builtin.import_tasks: install.yml

  # sites
  - ansible.builtin.import_tasks: sites.yml